import {
  AlertTriangle,
  Check,
  File,
  FileText,
  HelpCircle,
  Image,
  Loader2,
  LucideProps,
  MoreVertical,
  Plus,
  Settings,
  Terminal,
  Trash,
  Twitter,
  User,
  Sun,
  Moon,
  Laptop,
  X,
  Linkedin,
  Github,
  Mail,
  type Icon as LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Terminal,
  themeLight: Sun,
  linkedIn: Linkedin,
  mail: Mail,
  themeDark: Moon,
  themeSystem: Laptop,
  close: X,
  spinner: Loader2,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  help: HelpCircle,
  gitHub: Github,
  twitter: Twitter,
  check: Check,
};
